# Generated by Django 5.2 on 2025-04-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='user',
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
        migrations.DeleteModel(
            name='InsurancePolicy',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
